[package]
name = "schema_json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
schemars = "0.8.21"
jsonschema = "0.28.3"
boon = "0.6.1"
tempfile = "3.16.0"
